services:
  dev:
    image: node:22
    volumes:
      - .:/workspace
    working_dir: /workspace
    command: sleep infinity
    depends_on:
      - postgres  # 依赖项改为 postgres
      - mongo
    networks:
      - app-network